FROM openjdk:8-windowsservercore
# Copied basic dockerfile structure from Alex Smagin (https://github.com/asmagin/jenkins-on-windowsservercore)

# Jenkins default version (use --build-arg to override)
ARG JENKINS_VERSION=2.164.3
ARG JENKINS_UC=https://updates.jenkins.io

# Jenkins setup
ENV JENKINS_HOME=c:/jenkins

# Prevent setup wizard from running
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

# Promote arg to env
ENV JENKINS_UC=${JENKINS_UC}

# $ProgressPreference will disable download progress info and speed-up download
SHELL ["powershell", "-NoProfile", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; "]

# Install Jenkins master
RUN \
    $null = New-Item -ItemType Directory -Force -Path 'c:/jenkins'; \
    [Net.ServicePointManager]::SecurityProtocol = 'tls12'; \
    $uri = ('https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/{0}/jenkins-war-{0}.war' -f $env:JENKINS_VERSION); \
    $wc = New-Object -TypeName System.Net.WebClient; \
    $wc.DownloadFile($uri,'c:/jenkins.war')

COPY scripts/security.groovy c:/jenkins/init.groovy.d/security.groovy
COPY scripts/plugins.txt /scripts/plugins.txt
COPY scripts/startup.ps1 /scripts/startup.ps1

# For main web interface:
EXPOSE 8080

# Will be used by attached slave agents
EXPOSE 50000

CMD [ "powershell", "c:/scripts/startup.ps1" ]
