FROM jenkins/jenkins:latest

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

COPY scripts/security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy

RUN jenkins-plugin-cli \
    --plugins \
    build-with-parameters \
    cloudbees-folder

