FROM jenkins/jenkins:latest

ENV JAVA_OPTS="-Dhudson.udp=-1 -Djenkins.install.runSetupWizard=false --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.user=admin --argumentsRealm.roles.admin=admin"

RUN jenkins-plugin-cli \
    --plugins \
    build-with-parameters \
    cloudbees-folder

