FROM jenkins/jenkins:2.129

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

COPY scripts/security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy

COPY scripts/plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
